### ISSUE TITLE
which method to use for one direction stream?

### ISSUE THREAD

**Issue by freedreamer82** [vmware/transport-go#40]
Hi,

first of all compliments: I found your project very interesting but unfortunately the doc is quite poor.  I saw the examples mainly cover req/resp patterns but if I would to  design a stream where  one only pushes and another is listening to the events which api you should advise to use ?

I was expecting in the type EventBus interface  something  like SendNoReply or similar...

thanks 4 help.

      Marco

**Comment by jooskim** [comment]
Hello Marco,

Thanks for posting the issue. I definitely agree the need for better docs and examples, but rest assured, we have been working on straightforward and interactive tutorials! It seems that you have already checked out the basic hello world example on [our website](https://transport-bus.io/golang/hello-world). We do indeed have some real-world examples in the site, but they are actually nested under the TypeScript section so you may not have found them. I acknowledge that the Golang section of the tutorials is not as well covered as the TypeScript counterpart, and we will work on improving that.

That said for now, you can check out these examples:

https://transport-bus.io/ts/examples/ping-pong ([golang service](https://github.com/vmware/transport-go/blob/main/plank/services/ping-pong-service.go))
https://transport-bus.io/ts/examples/joke-service ([golang service](https://github.com/vmware/transport-go/blob/main/plank/services/joke-service.go))
https://transport-bus.io/ts/examples/stock-ticker ([golang service](https://github.com/vmware/transport-go/blob/main/plank/services/stock-ticker-service.go))
https://transport-bus.io/ts/examples/simple-stream ([golang service](https://github.com/vmware/transport-go/blob/main/plank/services/simple-stream-service.go))

These are our live end-to-end examples where the UI (React App using Transport TS) communicates with the backend (Plank using Transport Golang). In the interest of the pattern you would like to implement, I would recommend either  [PingPongService](https://github.com/vmware/transport-go/blob/main/plank/services/ping-pong-service.go) or [SimpleStreamService](https://github.com/vmware/transport-go/blob/main/plank/services/simple-stream-service.go).

The services above can then be initialized and plugged into the main Plank server instance like [this](https://github.com/vmware/transport-go/blob/main/plank/cmd/main.go#L37). Now, these examples are using Plank as their driver, and you CAN indeed build out your own system using the Transport event bus APIs only and not Plank, but still it is our best intention to encourage you to follow the patterns in the example code so you can leverage built-in features like lifecycle hooks etc. Let me know if you have further questions or confusion, I will be more than glad to discuss with you your use cases and help build out the patterns you need.

**Comment by jooskim** [comment]
I will also try to answer your question as much as I can. Let's start with simple examples. Say we have two actors. The publisher actor can use `SendResponseMessage()` method to send a message to the target channel, whereas the receiver on the receiving end should subscribe to the channel. This is done through calling `ListenStream()` (or `ListenOnce()` if you prefer it to be a single operation)

Here is a minimal snippet that explains above:

```go
// get bus instance
b := bus.GetBus()

// get channel manager
cm := b.GetChannelManager()

// create a new channel
myBusChan := "my-channel"
cm.CreateChannel(myBusChan)

handler, err := b.ListenStream(myBusChan)
if err != nil {
    utils.Log.Fatalln(err)
}

// set up handler (should be done in the receiving end)
handler.Handle(func(message *model.Message) {
    utils.Log.Infoln(message)
}, func(err error) {
    utils.Log.Fatalln(err)
})

...

// publisher sends a message to the target channel. (note the third parameter being nil means the message
// does not have a designated target and should be considered a broadcast meaning all subscribers to this channel
// should get the message.
b.SendResponseMessage(myBusChan, "your-payload", nil)
```

**Comment by freedreamer82** [comment]
hello @jooskim ,

everything is pretty clear. That is how actually I thought it worked...
if I can say the only thing weird is the name of the methods  : SendResponseMessage seems unusual to send a message without a request..maybe a generic Send() with the direction as parameter maybe it would have been  simpler , at least to me :)

Another 2 things :

1) I guess it should be possibile to have 1 publisher and more subs the channel , am I right ?
2) should be possibile to connect  mqtt instead of kafka/rabbit , it has the same pattern topic/data.

Thanks

    M.

**Comment by jooskim** [comment]
@freedreamer82 I can see where your confusion comes, and I think that's a valid one. In general, we make it a convention to use `SendResponseMessage()` as a way to send back the response payload, and `SendRequestMessage()` to send a request to the service. So in this light, my first example indeed may look strange. That is actually why our high-level APIs (`RequestOnce`, `RequestStream`, ListenRequestOnce`, `ListenRequestStream`, etc.) are preferred for request-response communications.

If the use case involves a broadcasting actor that just pumps out data without any requests to act on, then the first example should stand as a valid and efficient pattern.

To answer your other questions:
1. That is correct. Basically a bus channel has the 1:N relationship where you can have N subscribers
2. Absolutely. If you look at https://github.com/vmware/transport-go/blob/main/plank/cmd/broker_sample/app.go and https://github.com/vmware/transport-go/blob/main/plank/cmd/broker_sample/rabbitmq/over_amqp.go, the example is using the standard RabbitMQ package to make connections and send/receive payloads, so interfacing with other message brokers should be no problem at all. As an aside, https://github.com/vmware/transport-go/blob/main/plank/cmd/broker_sample/rabbitmq/over_stomp.go highlights the Transport's RabbitMQ integration via STOMP. As of today, we don't have such immediate integration with Kafka but it should be a straightforward feature work for us, as we have done exactly the same for the Transport Java version which supports RabbitMQ, Kafka, NATS and a VMware-internal message broker.

cc. @daveshanley

**Comment by freedreamer82** [comment]
Thanks @jooskim ,

As i told u the confusion came from methods' name : the high level APIs seem to be designed for req/resp pattern.
If you add a wrapper for broadcasting I think it not necessary to have a well documented API because all the others u did are self explanatory to me.

keep me updated.

thanks and (again) compliments for the repo

M.

**Comment by daveshanley** [comment]
@freedreamer82 I like your idea of a 'Broadcasting' wrapper. We can add something like this pretty easily - what would you expect the API to look like?

**Comment by jooskim** [comment]
Hey @freedreamer82 , I had a chat with @daveshanley and we think adding a stripped down (and renamed) version of `SendResponseMessage()` will work reasonably well for one-way messaging. In such a case you won't need to supply a destination UUID so as you suggested, the new method would look something like this:

```go
SendBroadcast(channelName string, payload interface{}) error
```

Then you can consume it the same way as above, by setting up a handler using `ListenStream()` then sending a payload with `SendBroadcast()`.

**Comment by freedreamer82** [comment]
it sounds ok to me.

thanks.

      Marco
