### ISSUE TITLE
README.md refers to appfabric.vmware.com which is not accessible.

### ISSUE THREAD

**Issue by strefethen** [vmware/transport-go#9]
The first para in this section of the README refers to appfabric.vmware.com.

https://github.com/vmware/transport-go#example-connecting-to-message-broker-and-using-galactic-channels

appfrabric.vmware.com returns "server not found".

**Comment by daveshanley** [comment]
Nice catch! That address isn't public, so we need to clean this up.

**Comment by daveshanley** [comment]
This has been resolved the README updated with a ready to run example.
